// Security tests for _build/firestore.rules (59 checks: who can read/write what).
// Run: npm i firebase-tools @firebase/rules-unit-testing firebase && npx firebase emulators:exec --only firestore --project demo-tf "node _build/tests/firestore-rules.test.mjs"
// (firebase.json needs "emulators": {"firestore": {"port": 8089}})
import { initializeTestEnvironment, assertSucceeds, assertFails } from '@firebase/rules-unit-testing';
import { readFileSync } from 'fs';
import { writeBatch, doc, setDoc, getDoc, getDocs, collection, updateDoc, deleteDoc, increment, serverTimestamp } from 'firebase/firestore';
const env = await initializeTestEnvironment({ projectId: 'demo-tf', firestore: { rules: readFileSync(new URL('../firestore.rules', import.meta.url), 'utf8'), host: '127.0.0.1', port: 8089 } });
const user = (uid, email, verified = true, prov = 'google.com') => env.authenticatedContext(uid, { email, email_verified: verified, firebase: { sign_in_provider: prov } }).firestore();
const alice = user('alice', 'alice@example.com'), bob = user('bob', 'bob@example.com');
const anon = user('anon1', undefined, false, 'anonymous');
const admin = user('max', 'infotrade@maxmaserati.com'), fakeAdmin = user('fake', 'infotrade@maxmaserati.com', false);
const nobody = env.unauthenticatedContext().firestore();
let pass = 0, fail = 0;
async function t(name, p, ok) { try { await (ok ? assertSucceeds(p) : assertFails(p)); pass++; } catch (e) { fail++; console.log('FAIL', name, e.message.slice(0, 160)); } }
const prof = { favs: ['a'], home: 'SW1A 1AA', alerts: true, alertsAt: '2026-10-06', feedback: false, email: 'alice@example.com', lang: 'en', updated: serverTimestamp() };
await t('profile own create', setDoc(doc(alice, 'profiles/alice'), prof), true);
await t('profile name merge', setDoc(doc(alice, 'profiles/alice'), { name: 'Alice' }, { merge: true }), true);
await t('profile foreign email', setDoc(doc(bob, 'profiles/bob'), { ...prof, email: 'victim@example.com' }), false);
await t('profile extra key', setDoc(doc(bob, 'profiles/bob'), { ...prof, email: 'bob@example.com', isAdmin: true }), false);
await t('profile huge favs', setDoc(doc(bob, 'profiles/bob'), { favs: Array(600).fill('x') }), false);
await t('profile other read', getDoc(doc(bob, 'profiles/alice')), false);
await t('profile anon-public read', getDoc(doc(nobody, 'profiles/alice')), false);
await t('profile admin read', getDoc(doc(admin, 'profiles/alice')), true);
await t('profile admin list', getDocs(collection(admin, 'profiles')), true);
await t('profile fake admin list', getDocs(collection(fakeAdmin, 'profiles')), false);
await t('profile user list', getDocs(collection(bob, 'profiles')), false);
await t('profile admin alerts off', updateDoc(doc(admin, 'profiles/alice'), { alerts: false }), true);
await t('profile admin edit name', updateDoc(doc(admin, 'profiles/alice'), { name: 'X' }), false);
await t('profile admin delete', deleteDoc(doc(admin, 'profiles/alice')), false);
const sub = e => ({ email: e, lang: 'en', area: '', consent: true, vf: true, at: serverTimestamp() });
await t('sub verified own', setDoc(doc(alice, 'subscribers/alice'), sub('alice@example.com')), true);
await t('sub someone else email', setDoc(doc(bob, 'subscribers/bob'), sub('victim@example.com')), false);
await t('sub anonymous', setDoc(doc(anon, 'subscribers/anon1'), sub('x@example.com')), false);
await t('sub unverified', setDoc(doc(user('carl', 'carl@example.com', false, 'password'), 'subscribers/carl'), sub('carl@example.com')), false);
await t('sub other uid', setDoc(doc(bob, 'subscribers/alice'), sub('bob@example.com')), false);
await t('sub no consent', setDoc(doc(bob, 'subscribers/bob'), { ...sub('bob@example.com'), consent: false }), false);
await t('sub public read', getDoc(doc(nobody, 'subscribers/alice')), false);
await t('sub user list', getDocs(collection(bob, 'subscribers')), false);
await t('sub admin list', getDocs(collection(admin, 'subscribers')), true);
await t('sub admin delete', deleteDoc(doc(admin, 'subscribers/alice')), true);
await t('sub admin create', setDoc(doc(admin, 'subscribers/zzz'), sub('z@example.com')), false);
await t('clicks +1', setDoc(doc(nobody, 'clicks/2026-10/k/xvd06'), { n: increment(1) }, { merge: true }), true);
await t('clicks +1 again', setDoc(doc(nobody, 'clicks/2026-10/k/xvd06'), { n: increment(1) }, { merge: true }), true);
await t('clicks +1 third', setDoc(doc(nobody, 'clicks/2026-10/k/xvd06'), { n: increment(1) }, { merge: true }), true);
await t('clicks value 3', getDoc(doc(nobody, 'clicks/2026-10/k/xvd06')).then(d => { if (d.data().n !== 3) throw new Error('n=' + d.data().n); }), true);
await t('clicks +5', setDoc(doc(nobody, 'clicks/2026-10/k/xvd06'), { n: increment(5) }, { merge: true }), false);
await t('clicks set big', setDoc(doc(nobody, 'clicks/2026-10/k/firsttable'), { n: 999 }), false);
await t('clicks extra field', setDoc(doc(nobody, 'clicks/2026-10/k/abc'), { n: 1, x: 1 }), false);
await t('clicks bad key', setDoc(doc(nobody, 'clicks/2026-10/k/BAD KEY'), { n: 1 }), false);
await t('clicks bad month', setDoc(doc(nobody, 'clicks/hack/k/xvd06'), { n: 1 }), false);
await t('clicks parent write', setDoc(doc(nobody, 'clicks/2026-10'), { a1: 1 }), false);
await t('clicks public list', getDocs(collection(nobody, 'clicks/2026-10/k')), true);
await t('clicks delete', deleteDoc(doc(admin, 'clicks/2026-10/k/xvd06')), false);
const entry = { vid: 'v1', name: 'Bellillo', area: 'Fulham', city: 'london', date: '2026-10-01', stars: 5, dish: 'Pizza', with: '', note: 'Great', photos: [], caps: [], best: 0, at: serverTimestamp() };
await t('diary own', setDoc(doc(alice, 'profiles/alice/diary/e1'), entry), true);
await t('diary other read', getDoc(doc(bob, 'profiles/alice/diary/e1')), false);
await t('diary admin read', getDoc(doc(admin, 'profiles/alice/diary/e1')), false);
await t('diary anon', setDoc(doc(anon, 'profiles/anon1/diary/e1'), entry), false);
await t('diary 5 photos', setDoc(doc(alice, 'profiles/alice/diary/e2'), { ...entry, photos: [1, 2, 3, 4, 5] }), false);
const visit = { vid: 'v1', name: 'Bellillo', area: 'Fulham', url: 'https://x', lang: 'en', at: serverTimestamp(), asked: false, expireAt: new Date(Date.now() + 2592e6) };
await t('visit own', setDoc(doc(alice, 'profiles/alice/visits/x1'), visit), true);
await t('visit extra', setDoc(doc(alice, 'profiles/alice/visits/x2'), { ...visit, junk: 1 }), false);
await t('profile owner delete', deleteDoc(doc(alice, 'profiles/alice')), true);
await t('ratings public read', getDoc(doc(nobody, 'ratings/v1')), true);
await t('likes public read', getDoc(doc(nobody, 'likes/v1')), true);
await t('random collection', setDoc(doc(alice, 'secrets/x'), { a: 1 }), false);
const like = (db, uid, on) => { const b = writeBatch(db); const by = doc(db, `likes/v9/by/${uid}`), c = doc(db, 'likes/v9');
  if (on) { b.set(by, { at: serverTimestamp() }); b.set(c, { n: increment(1) }, { merge: true }); } else { b.delete(by); b.set(c, { n: increment(-1) }, { merge: true }); } return b.commit(); };
await t('like anon', like(anon, 'anon1', true), true);
await t('like bob', like(bob, 'bob', true), true);
await t('like bob twice', like(bob, 'bob', true), false);
await t('like count 2', getDoc(doc(nobody, 'likes/v9')).then(d => { if (d.data().n !== 2) throw new Error('n=' + d.data().n); }), true);
await t('unlike bob', like(bob, 'bob', false), true);
await t('like +5 cheat', setDoc(doc(bob, 'likes/v9'), { n: 50 }), false);
const rate = (db, uid, stars, prev) => { const b = writeBatch(db); b.set(doc(db, `ratings/v9/by/${uid}`), { stars, at: serverTimestamp() });
  b.set(doc(db, 'ratings/v9'), { sum: increment(stars - prev), n: increment(prev ? 0 : 1) }, { merge: true }); return b.commit(); };
await t('rate alice 5', rate(alice, 'alice', 5, 0), true);
await t('rate alice change 3', rate(alice, 'alice', 3, 5), true);
await t('rate anon', rate(anon, 'anon1', 5, 0), false);
await t('rate 9 stars', rate(bob, 'bob', 9, 0), false);
await t('rate cheat sum', (() => { const b = writeBatch(bob); b.set(doc(bob, 'ratings/v9/by/bob'), { stars: 1, at: serverTimestamp() }); b.set(doc(bob, 'ratings/v9'), { sum: increment(50), n: increment(1) }, { merge: true }); return b.commit(); })(), false);
console.log(`rules tests: ${pass} passed, ${fail} failed`);
await env.cleanup();
process.exit(fail ? 1 : 0);
